services:
  app:
    build: ./app
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./images:/app/images
      - ./logs:/app/logs
    networks:
      - app-network

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./images:/images
      - ./logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network: